export const REACTWMJSMAP_SERVICE_SET_INFORMATION = 'REACTWMJSMAP_SERVICE_SET_INFORMATION';
export const REACTWMJSMAP_SERVICE_SET_LAYERS = 'REACTWMJSMAP_SERVICE_SET_LAYERS';
export const REACTWMJSMAP_SERVICE_LAYER_SET_STYLES = 'REACTWMJSMAP_SERVICE_LAYER_SET_STYLES';
export const REACTWMJSMAP_LAYER_CHANGE_STYLE = 'REACTWMJSMAP_LAYER_CHANGE_STYLE';
