export const ADD_ARTICLE = "ADD_ARTICLE";
export const LAYER_CHANGE_NAME = "LAYER_CHANGE_NAME";
export const LAYER_CHANGE_OPACITY = "LAYER_CHANGE_OPACITY";
export const LAYER_CHANGE_STYLE = "LAYER_CHANGE_STYLE";