export const ADD_ARTICLE = "ADD_ARTICLE";
export const LAYER_CHANGE_NAME = "LAYER_CHANGE_NAME";
export const LAYER_CHANGE_OPACITY = "LAYER_CHANGE_OPACITY";
export const LAYER_CHANGE_STYLE = "LAYER_CHANGE_STYLE";
export const SERVICE_SET_LAYERS = "SERVICE_SET_LAYERS";
export const LAYERMANAGER_TOGGLE_LAYERSELECTOR = "LAYERMANAGER_TOGGLE_LAYERSELECTOR";
export const SERVICE_LAYER_SET_STYLES = "SERVICE_LAYER_SET_STYLES";
export const LAYERMANAGER_TOGGLE_STYLESSELECTOR = "LAYERMANAGER_TOGGLE_STYLESSELECTOR";

